### ISSUE TITLE
Please add a license for permission

### ISSUE THREAD

**Issue by Poikilos** [hobby-overflow/WorldWideClocks#1]
Please add a license because: https://choosealicense.com/no-permission/

The easy way is:
- Log into GitHub, go to https://github.com/hobby-overflow/WorldWideClocks
- Add File, Create New File
  - Change the name to license.txt and GitHub's license chooser button will appear:
    - Click the "Choose a license template" button that appeared on the right then choose the one you want and add your name and 2012 if not autofilled.
  - Change the branch to (commit directly to) "master" at the bottom.
  - Click "Commit new file"

**Comment by hobby-overflow** [comment]
I'm Sorry the late Response.
Actually I can't decide.

MIT License is sounds good.
but my copyright notice is not necessary.
if there any recommend license, please tell me.

**Comment by Poikilos** [comment]
The only reason you would want GPL or LGPL is if you want to make sure people who make changes share them and that the forks of your program remain open source. You don't seem to be concerned about that for a small program like this that will probably be run in a Python intepreter. If you want MIT you can do that. If you actually don't even care about a copyright, you seem to want Creative Commons Zero v1.0 Universal.

**Comment by hobby-overflow** [comment]
Thanks so much for explained!
I decide CC0.
In this case, CC0 was ideal.

**Comment by Poikilos** [comment]
Thanks!
